[package]
name = "authnorization"
version = "0.1.0"
edition = "2021"
authors = ["Success Kingsley <hello@xosnrdev.tech>"]
description = "Basic authentication no authorization with rustful actix web"
license = "MIT"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "authnorization"

[dependencies]
chrono = { version = "0.4.38", features = ["clock", "serde"] }
serde = { version = "1.0.210", features = ["derive"] }
sqlx = { version = "0.8.2", default-features = false, features = [
  "runtime-tokio-rustls",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "migrate",
] }

uuid = { version = "1.10.0", features = ["v4", "serde"] }
log = "0.4.22"
env_logger = "0.11.5"
thiserror = "1.0.64"
dotenv = "0.15.0"
jsonwebtoken = "9.3.0"
argon2 = "0.5.3"
actix-web = "4.9.0"
validator = { version = "0.18.1", features = ["derive"] }
serde_json = "1.0.128"
regex = "1.11.0"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
strip = true
