services:
  db:
    image: postgres:13.16-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - target: $DATABASE_PORT
        published: $DATABASE_PORT
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

volumes:
  postgres-data:
    name: postgres-data
